DROP TABLE IF EXISTS trainer CASCADE;
DROP TABLE IF EXISTS attack CASCADE;
DROP TABLE IF EXISTS pokemon CASCADE;
DROP TABLE IF EXISTS typedesc CASCADE;
DROP TABLE IF EXISTS pokemonmoves CASCADE;
DROP TABLE IF EXISTS pokedex CASCADE;
DROP TABLE IF EXISTS super_effective CASCADE;
